"""add registry sync fields and ai_models table

Revision ID: e747a70f59e9
Revises: 72eba01334e0
Create Date: 2026-08-10 22:51:15.761417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e747a70f59e9'
down_revision: Union[str, Sequence[str], None] = '72eba01334e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('available', 'unavailable', name='availability_status'), server_default='available', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('mcps', sa.Column('status', sa.Enum('available', 'unavailable', name='availability_status'), server_default='available', nullable=False))
    op.add_column('mcps', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('skills', sa.Column('status', sa.Enum('available', 'unavailable', name='availability_status'), server_default='available', nullable=False))
    op.add_column('skills', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'last_synced_at')
    op.drop_column('skills', 'status')
    op.drop_column('mcps', 'last_synced_at')
    op.drop_column('mcps', 'status')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
    sa.Enum(name='availability_status').drop(op.get_bind(), checkfirst=True)
