"""widen agent_dependency dependency_id to string, add source

Revision ID: f64afce7bce0
Revises: 34fad9a918da
Create Date: 2026-08-11 01:16:36.499508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64afce7bce0'
down_revision: Union[str, Sequence[str], None] = '34fad9a918da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Manually adjusted from the autogenerated version:
    # - `source` needs a server_default so existing rows backfill to 'legacy'
    #   (every dependency added before this migration came from the first-party
    #   skills/mcps tables — there was no other source yet).
    # - the UUID -> String cast needs an explicit USING clause; Postgres won't do it
    #   implicitly.
    dependency_source = sa.Enum('legacy', 'registry', name='dependency_source')
    dependency_source.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'agent_dependencies',
        sa.Column('source', dependency_source, nullable=False, server_default='legacy'),
    )
    op.alter_column(
        'agent_dependencies',
        'dependency_id',
        existing_type=sa.UUID(),
        type_=sa.String(length=255),
        existing_nullable=False,
        postgresql_using='dependency_id::text',
    )
    op.drop_constraint(op.f('uq_agent_dependency'), 'agent_dependencies', type_='unique')
    op.create_unique_constraint('uq_agent_dependency', 'agent_dependencies', ['agent_slug', 'dependency_id', 'type', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Manually adjusted: drops any registry-sourced rows first (their dependency_id
    # is never a valid UUID, e.g. an external MCP tool key — the cast back to UUID
    # would fail on them), then reverses the rest the same way upgrade() did.
    op.execute("DELETE FROM agent_dependencies WHERE source = 'registry'")
    op.drop_constraint('uq_agent_dependency', 'agent_dependencies', type_='unique')
    op.create_unique_constraint(op.f('uq_agent_dependency'), 'agent_dependencies', ['agent_slug', 'dependency_id', 'type'], postgresql_nulls_not_distinct=False)
    op.alter_column(
        'agent_dependencies',
        'dependency_id',
        existing_type=sa.String(length=255),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using='dependency_id::uuid',
    )
    op.drop_column('agent_dependencies', 'source')
    sa.Enum(name='dependency_source').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
